pipeline:
  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-bdd-base .
    when:
      event: push
  push:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+pttg" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-bdd-base quay.io/ukhomeofficedigital/pttg-bdd-base:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-bdd-base:build-$${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master